### Registro User
POST http://127.0.0.1:8000/api/registro
Content-Type: application/json
Accept: application/json

{
    "name": "Oscar",
    "email": "oscar@gmail.com",
    "password": "oscar12345",
    "password_confirmation": "oscar12345"
}


### Login User
POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
	"email": "oscar@gmail.com",
	"password": "oscar12345"
}

### Perfil
GET http://127.0.0.1:8000/api/perfil
Content-Type: application/json
Accept: application/json

### Logout
POST http://127.0.0.1:8000/api/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer 14|pFp3L373q9zZAvltG1oxveRoVDWB2QRcXNBIiy4N
